# Generated by Django 5.2.9 on 2025-12-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='color',
            new_name='primaryColor',
        ),
        migrations.AddField(
            model_name='colors',
            name='secondaryColor',
            field=models.CharField(default='#ffffff', max_length=50),
            preserve_default=False,
        ),
    ]
