# Generated by Django 5.2.9 on 2025-12-09 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_color_colors_primarycolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='instituteID',
        ),
        migrations.AddField(
            model_name='institute',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.colors'),
        ),
    ]
