# Generated by Django 5.2.9 on 2025-12-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_colors_instituteid_institute_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
