# Generated by Django 5.2.9 on 2025-12-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_instituteid_user_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
