# Generated by Django 5.2.9 on 2025-12-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_institute_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('configID', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=10)),
                ('threshold_value', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
            ],
        ),
    ]
