# Generated by Django 5.2.8 on 2025-11-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('fLastName', models.CharField(max_length=100)),
                ('sLastName', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('instituteID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('colorID', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50)),
                ('instituteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('instituteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=150)),
                ('typeDescription', models.TextField(blank=True, null=True)),
                ('stationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pollutantValue', models.FloatField()),
                ('pollutantLevels', models.CharField(max_length=50)),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('stationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegisterInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'unique_together': {('userID', 'instituteID')},
            },
        ),
        migrations.CreateModel(
            name='UserRegisterStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'unique_together': {('userID', 'stationID')},
            },
        ),
    ]
